import type {
  StudentProfile,
  FacultyProfile,
  AdminProfile,
  SubjectAttendance,
  AttendanceRecord,
  TimetableSlot,
  Announcement,
  FacultyClassSchedule,
  StudentRosterItem,
  DepartmentSummary,
} from '../types';

export const DEMO_STUDENT: StudentProfile = {
  id: 'u-student-1',
  name: 'Alex Johnson',
  email: 'alex.johnson@college.edu',
  role: 'student',
  rollNumber: 'CS2024-042',
  hallTicketNumber: 'HT2024-CS042',
  course: 'B.Sc Computer Science',
  semester: 4,
  section: 'Section A',
  academicYear: '2025-2026',
  department: 'Computer Science & Engineering',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const DEMO_FACULTY: FacultyProfile = {
  id: 'u-faculty-1',
  name: 'Dr. Sarah Mitchell',
  email: 'sarah.mitchell@college.edu',
  role: 'faculty',
  facultyId: 'FAC-CS-108',
  designation: 'Associate Professor',
  department: 'Computer Science & Engineering',
  assignedSubjects: ['CS301 - Data Structures', 'CS304 - Database Systems', 'CS402 - Cloud Computing'],
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
};

export const DEMO_ADMIN: AdminProfile = {
  id: 'u-admin-1',
  name: 'Dean Dr. Robert Vance',
  email: 'admin@college.edu',
  role: 'admin',
  adminId: 'ADM-EXEC-001',
  title: 'Dean of Academic Affairs',
  department: 'University Administration',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
};

export const STUDENT_SUBJECTS: SubjectAttendance[] = [
  {
    id: 'sub-1',
    code: 'CS301',
    name: 'Data Structures & Algorithms',
    credits: 4,
    facultyName: 'Dr. Sarah Mitchell',
    department: 'Computer Science',
    semester: 4,
    presentClasses: 42,
    totalClasses: 50,
    percentage: 84.0,
    tier: 'Good',
  },
  {
    id: 'sub-2',
    code: 'MA201',
    name: 'Discrete Mathematics & Logic',
    credits: 4,
    facultyName: 'Prof. David Chen',
    department: 'Mathematics',
    semester: 4,
    presentClasses: 46,
    totalClasses: 50,
    percentage: 92.0,
    tier: 'Excellent',
  },
  {
    id: 'sub-3',
    code: 'CS304',
    name: 'Database Management Systems',
    credits: 3,
    facultyName: 'Dr. Sarah Mitchell',
    department: 'Computer Science',
    semester: 4,
    presentClasses: 38,
    totalClasses: 48,
    percentage: 79.2,
    tier: 'Warning',
  },
  {
    id: 'sub-4',
    code: 'CS305',
    name: 'Computer Networks & Security',
    credits: 3,
    facultyName: 'Prof. Elena Rostova',
    department: 'Computer Science',
    semester: 4,
    presentClasses: 34,
    totalClasses: 46,
    percentage: 73.9,
    tier: 'Critical',
  },
];

export const STUDENT_ATTENDANCE_HISTORY: AttendanceRecord[] = [
  {
    id: 'att-1',
    date: '2026-09-11',
    subjectId: 'sub-1',
    subjectCode: 'CS301',
    subjectName: 'Data Structures & Algorithms',
    period: 1,
    faculty: 'Dr. Sarah Mitchell',
    status: 'Present',
  },
  {
    id: 'att-2',
    date: '2026-09-11',
    subjectId: 'sub-2',
    subjectCode: 'MA201',
    subjectName: 'Discrete Mathematics & Logic',
    period: 2,
    faculty: 'Prof. David Chen',
    status: 'Present',
  },
  {
    id: 'att-3',
    date: '2026-09-10',
    subjectId: 'sub-4',
    subjectCode: 'CS305',
    subjectName: 'Computer Networks & Security',
    period: 3,
    faculty: 'Prof. Elena Rostova',
    status: 'Absent',
    remarks: 'Unexcused medical absence',
  },
  {
    id: 'att-4',
    date: '2026-09-10',
    subjectId: 'sub-3',
    subjectCode: 'CS304',
    subjectName: 'Database Management Systems',
    period: 4,
    faculty: 'Dr. Sarah Mitchell',
    status: 'Present',
  },
  {
    id: 'att-5',
    date: '2026-09-09',
    subjectId: 'sub-1',
    subjectCode: 'CS301',
    subjectName: 'Data Structures & Algorithms',
    period: 1,
    faculty: 'Dr. Sarah Mitchell',
    status: 'Present',
  },
  {
    id: 'att-6',
    date: '2026-09-08',
    subjectId: 'sub-4',
    subjectCode: 'CS305',
    subjectName: 'Computer Networks & Security',
    period: 2,
    faculty: 'Prof. Elena Rostova',
    status: 'Absent',
  },
];

export const STUDENT_WEEKLY_TREND = [
  { week: 'Wk 1', attendance: 88, target: 75 },
  { week: 'Wk 2', attendance: 85, target: 75 },
  { week: 'Wk 3', attendance: 81, target: 75 },
  { week: 'Wk 4', attendance: 86, target: 75 },
  { week: 'Wk 5', attendance: 80, target: 75 },
  { week: 'Wk 6', attendance: 82.5, target: 75 },
];

export const TODAY_TIMETABLE: TimetableSlot[] = [
  {
    id: 'tt-1',
    time: '09:30 AM - 10:30 AM',
    period: 1,
    day: 'Friday',
    subjectCode: 'CS301',
    subjectName: 'Data Structures & Algorithms',
    room: 'Lab Complex 302',
    faculty: 'Dr. Sarah Mitchell',
  },
  {
    id: 'tt-2',
    time: '10:45 AM - 11:45 AM',
    period: 2,
    day: 'Friday',
    subjectCode: 'MA201',
    subjectName: 'Discrete Mathematics',
    room: 'Lecture Hall 104',
    faculty: 'Prof. David Chen',
  },
  {
    id: 'tt-3',
    time: '12:30 PM - 01:30 PM',
    period: 3,
    day: 'Friday',
    subjectCode: 'CS304',
    subjectName: 'Database Management Systems',
    room: 'Seminar Room 2',
    faculty: 'Dr. Sarah Mitchell',
  },
  {
    id: 'tt-4',
    time: '02:00 PM - 03:00 PM',
    period: 4,
    day: 'Friday',
    subjectCode: 'CS305',
    subjectName: 'Computer Networks & Security',
    room: 'Tech Wing 401',
    faculty: 'Prof. Elena Rostova',
  },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: '⚠️ Mid-Semester Attendance Eligibility Warning',
    description:
      'Students with overall attendance below 75% as of September 25th will be ineligible to appear for Mid-Term Examinations. Please check the calculator widget on your dashboard to calculate necessary classes.',
    date: 'Sep 10, 2026',
    author: 'Office of the Dean of Academic Affairs',
    priority: 'Urgent',
  },
  {
    id: 'ann-2',
    title: 'Special Seminar: Scalable Distributed Systems at Scale',
    description:
      'Guest lecture hosted by the Department of Computer Science this upcoming Wednesday at 3:00 PM in the Main Auditorium.',
    date: 'Sep 09, 2026',
    author: 'Dr. Sarah Mitchell (HOD In-Charge)',
    priority: 'Important',
  },
  {
    id: 'ann-3',
    title: 'Campus Central Library Weekend Extended Study Hours',
    description:
      'The central digital library will remain open until 10:00 PM during the pre-examination study week.',
    date: 'Sep 07, 2026',
    author: 'Library Administration',
    priority: 'Normal',
  },
];

export const FACULTY_SCHEDULE: FacultyClassSchedule[] = [
  {
    id: 'fcs-1',
    subjectId: 'sub-1',
    subjectCode: 'CS301',
    subjectName: 'Data Structures & Algorithms',
    section: 'B.Sc CS - Section A',
    course: 'B.Sc Computer Science',
    time: '09:30 AM - 10:30 AM',
    period: 1,
    room: 'Room 302',
    totalStudents: 45,
    attendanceCompleted: false,
  },
  {
    id: 'fcs-2',
    subjectId: 'sub-3',
    subjectCode: 'CS304',
    subjectName: 'Database Management Systems',
    section: 'B.Sc CS - Section B',
    course: 'B.Sc Computer Science',
    time: '11:30 AM - 12:30 PM',
    period: 3,
    room: 'Room 204',
    totalStudents: 42,
    attendanceCompleted: true,
  },
  {
    id: 'fcs-3',
    subjectId: 'sub-5',
    subjectCode: 'CS402',
    subjectName: 'Cloud Computing & Virtualization',
    section: 'M.Sc CS - Section A',
    course: 'M.Sc Computer Science',
    time: '02:00 PM - 03:00 PM',
    period: 5,
    room: 'Lab 408',
    totalStudents: 38,
    attendanceCompleted: false,
  },
];

export const INITIAL_STUDENT_ROSTER: StudentRosterItem[] = [
  { id: 'st-01', rollNumber: 'CS2024-001', name: 'Aarav Patel', status: 'Present', currentPercentage: 88.5 },
  { id: 'st-02', rollNumber: 'CS2024-002', name: 'Aditi Rao', status: 'Present', currentPercentage: 94.2 },
  { id: 'st-03', rollNumber: 'CS2024-003', name: 'Alex Johnson', status: 'Present', currentPercentage: 84.0 },
  { id: 'st-04', rollNumber: 'CS2024-004', name: 'Ananya Sharma', status: 'Present', currentPercentage: 91.0 },
  { id: 'st-05', rollNumber: 'CS2024-005', name: 'Brian Miller', status: 'Absent', currentPercentage: 72.4 },
  { id: 'st-06', rollNumber: 'CS2024-006', name: 'Chloe Davies', status: 'Present', currentPercentage: 85.6 },
  { id: 'st-07', rollNumber: 'CS2024-007', name: 'David Kumar', status: 'Present', currentPercentage: 78.0 },
  { id: 'st-08', rollNumber: 'CS2024-008', name: 'Emily Zhang', status: 'Present', currentPercentage: 96.0 },
  { id: 'st-09', rollNumber: 'CS2024-009', name: 'Farhan Ali', status: 'Absent', currentPercentage: 68.5 },
  { id: 'st-10', rollNumber: 'CS2024-010', name: 'Grace O\'Connor', status: 'Present', currentPercentage: 89.2 },
  { id: 'st-11', rollNumber: 'CS2024-011', name: 'Hassan Raza', status: 'Present', currentPercentage: 81.5 },
  { id: 'st-12', rollNumber: 'CS2024-012', name: 'Ishaan Verma', status: 'Present', currentPercentage: 74.0 },
  { id: 'st-13', rollNumber: 'CS2024-013', name: 'Jessica Taylor', status: 'Present', currentPercentage: 87.3 },
  { id: 'st-14', rollNumber: 'CS2024-014', name: 'Karthik Nair', status: 'Present', currentPercentage: 90.5 },
  { id: 'st-15', rollNumber: 'CS2024-015', name: 'Liam Brown', status: 'Absent', currentPercentage: 69.1 },
];

export const LOW_ATTENDANCE_WATCHLIST = [
  { id: 'w-1', name: 'Farhan Ali', rollNumber: 'CS2024-009', subject: 'Data Structures', attendance: 68.5, classesMissed: 14 },
  { id: 'w-2', name: 'Liam Brown', rollNumber: 'CS2024-015', subject: 'Data Structures', attendance: 69.1, classesMissed: 13 },
  { id: 'w-3', name: 'Brian Miller', rollNumber: 'CS2024-005', subject: 'Database Systems', attendance: 72.4, classesMissed: 12 },
  { id: 'w-4', name: 'Ishaan Verma', rollNumber: 'CS2024-012', subject: 'Computer Networks', attendance: 74.0, classesMissed: 11 },
];

export const DEPARTMENTS_DATA: DepartmentSummary[] = [
  {
    id: 'dept-1',
    name: 'Computer Science & Engineering',
    code: 'CSE',
    studentCount: 420,
    facultyCount: 28,
    averageAttendance: 82.4,
    lowAttendanceCount: 38,
  },
  {
    id: 'dept-2',
    name: 'Electronics & Communication',
    code: 'ECE',
    studentCount: 340,
    facultyCount: 22,
    averageAttendance: 84.1,
    lowAttendanceCount: 24,
  },
  {
    id: 'dept-3',
    name: 'Mechanical Engineering',
    code: 'ME',
    studentCount: 290,
    facultyCount: 18,
    averageAttendance: 78.6,
    lowAttendanceCount: 41,
  },
  {
    id: 'dept-4',
    name: 'Civil Engineering',
    code: 'CE',
    studentCount: 220,
    facultyCount: 14,
    averageAttendance: 80.5,
    lowAttendanceCount: 19,
  },
  {
    id: 'dept-5',
    name: 'Biotechnology',
    code: 'BT',
    studentCount: 180,
    facultyCount: 12,
    averageAttendance: 86.2,
    lowAttendanceCount: 11,
  },
];

export const COLLEGE_MONTHLY_TREND = [
  { month: 'Apr', averageAttendance: 84.2, threshold: 75 },
  { month: 'May', averageAttendance: 83.5, threshold: 75 },
  { month: 'Jun', averageAttendance: 81.0, threshold: 75 },
  { month: 'Jul', averageAttendance: 80.4, threshold: 75 },
  { month: 'Aug', averageAttendance: 82.1, threshold: 75 },
  { month: 'Sep', averageAttendance: 81.8, threshold: 75 },
];
